version: "4.2"

volumes:
  db-data:

services:
  django:
    build: .
    ports:
      - 4545:4545
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /entrypoint.sh'
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=mysuperlongsecurepassword
      - POSTGRES_DB=app
    volumes: # Where postgres saves data
      - db-data:/var/lib/postgressql/data
    ports:
      - 5430:5432
